[![Cypress Tests](https://github.com/Rafael-Albano/cypress-basic/actions/workflows/main.yml/badge.svg)](https://github.com/Rafael-Albano/cypress-basic/actions/workflows/main.yml)

name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          run: yarn
          test: yarn test
          
